project:
  type: website
  output-dir: ../work

website:
  title: "hellomister"
  navbar:
    left:
      - text: "home"
        href: ../index.html
      - text: "about"
        href: ../about.html
      - text: "work"
        href: index.qmd
      - text: "things"
        href: ../not_ready_yet2.html

format:
  html:
    theme:
      - default            # base theme
      - assets/styles.scss # your SCSS compiled & merged (not linked as .scss)
    include-in-header: |
      <link rel="stylesheet" href="https://use.typekit.net/rtn8uaf.css">
    title-block-style: none
    title-block-banner: false