project:
  type: website
  output-dir: ../work

website:
  title: 
  navbar: false   # turn Quarto’s navbar OFF

format:
  html:
    theme: default
    include-in-header: |
      <link rel="stylesheet" href="https://use.typekit.net/rtn8uaf.css">
      <link rel="stylesheet" href="assets/header.css">
    include-before-body: header.html
    title-block-style: none
    title-block-banner: false 